### ISSUE TITLE
Multiple config files

### ISSUE THREAD

**Issue by etcook** [yogiben/meteor-starter#87]
Why is there a /both/config/_config.coffee and /lib/config/_config.coffee? Furthermore, it seems that some of the vars that the templates require access to aren't working out of the box, since they're not present in both (but they're in lib). E.g. dashboardRoute

**Comment by chmac** [comment]
The one in `lib/` is loaded first and there's no merging going on, so it will be overwritten by the other one.

**Comment by etcook** [comment]
@chmac Sorry if this is a stupid question, but why do they both exist?

**Comment by chmac** [comment]
I came to report the same bug and saw your ticket! I guess it's a bug.

**Comment by justintieu** [comment]
From what I've observed, it seems like the config file in the lib directory should be the default config file. The one in the both directory overrides what config file in the lib directory contains. I'd assume that all configuration should be done through the config file in the both directory. 

I've also noticed that if you want to specify something from the config file in the lib directory, it has to be prefixed with `Config.`

**Comment by chmac** [comment]
@justintieu True, the file in `both/` will **overwrite** the file in `lib/`, but it will not **extend** it. So anything you set in `lib/` will be 100% ignored. The file is therefore 100% redundant. Maybe it exists to show the available config options, but I don't see that documented anywhere.

If it's supposed to be the default config file, then the `both/` config file should use some kind of `_.extend()` or comparable operation to overwrite the defaults, rather than simply obliterating the existing value of `@Config`.

**Comment by snamoah** [comment]
@etcook @chmac @justintieu That's right. It's been fixed now... see [#101](https://github.com/yogiben/meteor-starter/pull/101)
